// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BookList: typeof import('./src/components/BookList.vue')['default']
    ICarbonSearch: typeof import('~icons/carbon/search')['default']
    ICarbonUserAvatarFilledAlt: typeof import('~icons/carbon/user-avatar-filled-alt')['default']
    IFluentPeopleCommunity16Filled: typeof import('~icons/fluent/people-community16-filled')['default']
    IGrommetIconsFormNext: typeof import('~icons/grommet-icons/form-next')['default']
    IIcBaselineHeadsetMic: typeof import('~icons/ic/baseline-headset-mic')['default']
    IMdiBookshelf: typeof import('~icons/mdi/bookshelf')['default']
    IMdiLogout: typeof import('~icons/mdi/logout')['default']
    IPhUser: typeof import('~icons/ph/user')['default']
    IPhUserBold: typeof import('~icons/ph/user-bold')['default']
    IPhUserCircleThin: typeof import('~icons/ph/user-circle-thin')['default']
    IRiUserLine: typeof import('~icons/ri/user-line')['default']
    IUilFeedback: typeof import('~icons/uil/feedback')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpace: typeof import('naive-ui')['NSpace']
  }
}

export { }
